AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to run cfn_nag as a step in a pipeline
Parameters:
  PipelineBucketName:
    Description: 'The bucket name to allow access to read artifacts from - the CodePipeline Artifact Store'
    Type: String
  RuleBucketName:
    Description: 'The bucket to load custom nag rules from'
    Type: String
    Default: ''
  RuleBucketPrefix:
    Description: 'The prefix in the bucket to load custom nag rules from'
    Type: String
    Default: ''

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      PipelineBucketName:
        default: 'CodePipeline Artifact Bucket Name'
      RuleBucketName:
        default: 'Custom Rules Bucket Name'
      RuleBucketPrefix:
        default: 'Custom Rules Bucket Prefix'

Conditions:
  NoCustomRules: !Equals [ !Ref RuleBucketName, '' ]

Resources:
  CfnNagFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-nag-pipeline
      Runtime: ruby2.7
      MemorySize: 1024
      Timeout: 300
      CodeUri:  lib
      Handler: handler.handler
      Environment:
        Variables:
          RULE_BUCKET_NAME: !Ref RuleBucketName
          RULE_BUCKET_PREFIX: !Ref RuleBucketPrefix

      Policies:
      - CodePipelineLambdaExecutionPolicy: {}
      - S3ReadPolicy:
          BucketName: !Ref PipelineBucketName
      - S3ReadPolicy:
          BucketName: !Ref RuleBucketName